Job execution
OpenBotsAI/OpenBots.Agent pull request #2
Opened 2020-10-07 15:45 UTC by openbots-ab

- Job Execution from Server (Timed Polling) feature has been added
- Long Polling feature (SignalR) is being developed

**Note:** It's being updated, please don't approve yet.

2020-10-12 15:50 UTC, openbots-ff approved these changes

2020-10-13 04:57 UTC, openbots-ch requested changes

2020-10-13 19:14 UTC, openbots-ab commented on OpenBots.Executor/Engine/EngineHandler.cs
> +            engineParams[0] = new Logging().CreateFileLogger(logFile, Serilog.RollingInterval.Day);
This provides engine execution logs.
What I am getting from the **core process logs** is the logs that will be sent to **ProcessExecutionLogs** Endpoint on starting and finishing the process execution. Am I right?

2020-10-13 19:17 UTC, openbots-ab commented on OpenBots.Service.Client/Manager/Execution/ExecutionManager.cs
> +                        new Operation(){ Op = "replace", Path = "/message", Value = "Job is failed"},
That's in the to do list.

2020-10-15 14:28 UTC, openbots-ch commented on OpenBots.Executor/Engine/EngineHandler.cs
> +            engineParams[0] = new Logging().CreateFileLogger(logFile, Serilog.RollingInterval.Day);
Logs obtained during the process execution go to the ProcessLogs Endpoint. ProcessExecutionLogs are used to signal the start and stop of a job.

2020-10-26 19:19 UTC, openbots-ch approved these changes

2020-10-26 19:19 UTC, merged